### ISSUE TITLE
Guess-my-number-game.py

### ISSUE THREAD

**Issue by axp0900** [Brian-Nduhiu/beginner-projects#2]
# Create the guess-my-number-game.py project
## <ins>Requirements</ins>
- System should be able to generate a random number from a range
- Use a set of sequences where the User guesses the number from a certain range of numbers
- User gets a limited amount of tries

**Comment by axp0900** [comment]
@Brian-Nduhiu I would like to work on this issue if possible

**Comment by Brian-Nduhiu** [comment]
Sure, Ill highly appreciate your input with this project.

**Comment by Brian-Nduhiu** [comment]
Kindly perform a pull request and ill review your code to merge it with the master.
